// module-federation/host-demo-react/src/App.tsx
import "./App.css";
import React from "react";
import ReactDOM from "react-dom";
import Runtime from "runtime";
// import { init, loadRemote } from "@module-federation/enhanced/runtime";

const options = {
  name: "host_storybook",
  remotes: [
    {
      name: "remote_react_rsbuild",
      entry: "http://localhost:2001/mf-manifest.json",
    },
    {
      name: "remote_react_vite",
      entry: "http://localhost:2002/mf-manifest.json",
    },
  ],
  shared: {
    react: {
      version: "18.3.1",
      lib: () => React,
      // shareConfig: { singleton: true, requiredVersion: "18.5" },
    },
    "react-dom": {
      version: "18.3.1",
      lib: () => ReactDOM,
      // shareConfig: { singleton: true, requiredVersion: "18.5" },
    },
  },
};

// init(options);

const runtime = new Runtime(options);
const RemoteReactRsbuildButtonModel = runtime.loadRemote("remote_react_rsbuild/Button");

const RemoteReactRsbuildButton = React.lazy(() => RemoteReactRsbuildButtonModel);

const RemoteReactViteButtonModel = runtime.loadRemote("remote_react_vite/Button");

const RemoteReactViteButton = React.lazy(() => RemoteReactViteButtonModel);

const App = () => {
  return (
    <div className="content">
      <h1>host-demo-react</h1>
      <p>remote-react-rsbuild</p>
      <RemoteReactRsbuildButton type="primary" name="弹框1" />
      <p>remote-react-vite</p>
      <RemoteReactViteButton type="primary" name="弹框2" />
    </div>
  );
};

export default App;

// module-federation/host-demo-vue/src/App.vue
<script setup lang="ts">
import { init, loadRemote } from "@module-federation/enhanced/runtime";
import { defineAsyncComponent } from "vue";

const options = {
  name: "host_vue",
  remotes: [
    {
      name: "remote_vue_vite",
      entry: "http://localhost:3001/mf-manifest.json",
    },
  ],
  shared: {
    // react: {
    //   version: "18.3.1",
    //   lib: () => React,
    //   // shareConfig: { singleton: true, requiredVersion: "18.5" },
    // },
    // "react-dom": {
    //   version: "18.3.1",
    //   lib: () => ReactDOM,
    //   // shareConfig: { singleton: true, requiredVersion: "18.5" },
    // },
  },
};

init(options);

const RemoteReactRsbuildButton = defineAsyncComponent(() => loadRemote("remote_vue_vite/Button"));
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <h1>Vue Host</h1>
  <h2>Remote Vue By Vite</h2>
  <RemoteReactRsbuildButton type="primary" name="hello" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
